const CATEGORY_MAP = {
  // Plural forms
  'restaurants':  'catering.restaurant',
  'cafes':        'catering.cafe',
  'bars':         'catering.bar',
  'hotels':       'accommodation.hotel',
  'salons':       'service.beauty.hairdresser',
  'barbershops':  'service.beauty.barbershop',
  'gyms':         'sport.fitness',
  'pharmacies':   'healthcare.pharmacy',
  'clinics':      'healthcare.clinic',
  'dentists':     'healthcare.dentist',
  'lawyers':      'office.lawyer',
  'accountants':  'office.accountant',
  'plumbers':     'service.plumber',
  'electricians': 'service.electrician',
  'mechanics':    'service.vehicle.car_repair',
  'shops':        'commercial.shopping_mall',
  'supermarkets': 'commercial.supermarket',
  'bakeries':     'catering.bakery',
  'schools':      'education.school',
  // Singular forms (for convenience)
  'restaurant':   'catering.restaurant',
  'cafe':         'catering.cafe',
  'bar':          'catering.bar',
  'hotel':        'accommodation.hotel',
  'salon':        'service.beauty.hairdresser',
  'barbershop':   'service.beauty.barbershop',
  'gym':          'sport.fitness',
  'pharmacy':     'healthcare.pharmacy',
  'clinic':       'healthcare.clinic',
  'dentist':      'healthcare.dentist',
  'lawyer':       'office.lawyer',
  'accountant':   'office.accountant',
  'plumber':      'service.plumber',
  'electrician':  'service.electrician',
  'mechanic':     'service.vehicle.car_repair',
  'shop':         'commercial.shopping_mall',
  'supermarket':  'commercial.supermarket',
  'bakery':       'catering.bakery',
  'school':       'education.school',
  'all':          null
}

const CATEGORY_BUCKETS = [
  'catering.restaurant,catering.cafe',
  'catering.fast_food,catering.bar',
  'catering.bakery',
  'commercial.supermarket',
  'commercial.shopping_mall',
  'commercial.clothing',
  'commercial.electronics',
  'service.beauty',
  'service.vehicle',
  'service.plumber,service.electrician',
  'healthcare.pharmacy',
  'healthcare.clinic,healthcare.dentist',
  'education.school',
  'accommodation.hotel',
  'sport.fitness,sport.stadium',
  'office.lawyer,office.accountant',
  'public_transport',
]

export { CATEGORY_MAP, CATEGORY_BUCKETS }
